### ISSUE TITLE
Updating PyPI package version, release version vs. beta tracking

### ISSUE THREAD

**Issue by pasta41** [socialfoundations/folktables#34]
Hi there,

First off, thank you all so much for the work that has gone into this -- it is the best ML-related research repo I've every worked with, in terms of both code quality and documentation.  

I have been playing around with the codebase and tried installing from `pip` instead of via source. Some of the abstract library methods weren't working correctly  (e.g., `BasicProblem.df_to_pandas`). I naturally did the lazy thing:  I tried  to install from source and test if this was a staleness/ version mismatch issue with PyPI, and (at least for the methods I was playing with), this in fact does seem to be the case. Would it be possible to use the release tagging feature in Github so that it's possible to track if the version in PyPI is up to date with the latest stable version, and to distinguish from dev (and to update the version in PyPI)? 

Also, as an aside, it looks like `setup.py` is not completely configured correctly (installing from source was actually the third thing I tried; the second was to `pip install` via `git` into a `conda` environment, but `setup.py` crashed.)

Lastly, I would be happy to open a PR for some of these small things, if that would be helpful/welcome.

Best,
Cooper

**Comment by mrtzh** [comment]
Hi Cooper,

thank you so much for your kind words. We really appreciate it!

Please do send along a PR with these suggested changes. I just merged a pull request that should've addressed one of the setup issues. I'm also trying to get the PyPy API key to make updates automatic.

Best wishes,
Moritz

**Comment by mrtzh** [comment]
I think I managed to update the PyPI version. Installing from `pip` should work again.

**Comment by pasta41** [comment]
Awesome, thanks Moritz! I should have some time to test it this week and see if the issues I was observing are still present. If so, I'll open a PR.

Best,
Cooper
